version: '3'

services:
  mysql:
    image: percona/percona-server:8.0.17
    container_name: javainterview-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - TZ=Europe/Moscow
    ports:
      - "3311:3306"

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    extra_hosts: ['host.docker.internal:host-gateway']
    restart: always
    ports:
      - "9411:9411"

  rabbitmq:
    container_name: demo-rabbitmq
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"

  demo-db:
    container_name: demo-db
    image: postgres:14.6
    environment:
      POSTGRES_DB: demo-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "55326:5432"
    volumes:
      - demo-db:/var/lib/postgres
    command: [ "postgres", "-c", "log_statement=all" ]

  demo-db-test:
    container_name: demo-db-test
    image: postgres:14.6
    environment:
      POSTGRES_DB: test-db
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "55328:5432"
    volumes:
      - demo-db-test:/var/lib/postgres
    command: [ "postgres", "-c", "log_statement=all" ]

volumes:
  demo-db:
  demo-db-test:
