version: '3'

services:
  mysql:
    image: percona/percona-server:8.0.17
    container_name: javainterview-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - TZ=Europe/Moscow
    ports:
      - "3311:3306"

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    extra_hosts: ['host.docker.internal:host-gateway']
    restart: always
    ports:
      - "9411:9411"

  rabbitmq:
    container_name: demo-rabbitmq
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"
