server:
  port: 5006

spring:
  application:
    name: DemoApp
  config:
    import: db_postgresql.properties, rabbit.yml, api_integration.yml
  boot:
    admin:
      client:
        url: http://localhost:${server.port}

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0

# Swagger
springdoc:
  swagger-ui:
    path: /api-docs