server:
  port: 5006

spring:
  application:
    name: DemoApp
  boot:
    admin:
      client:
        url: http://localhost:${server.port}

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3311}/${MYSQL_DATABASE:test-db}?useUnicode=true&allowMultiQueries=true&characterEncoding=UTF-8&autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Europe/Moscow
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER:user}
    password: ${MYSQL_PASSWORD:user}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: 'true'
    open-in-view: 'false'
#    show-sql: true

  rabbitmq:
    password: ${RABBITMQ_PASSWORD:guest}
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    listener:
      simple:
        retry:
          initial-interval: '1000'
          enabled: 'true'
          multiplier: '2.0'
          max-attempts: '3'
    virtual-host: ${RABBITMQ_VHOST:/}

# RabbitMQ: Queues
amqp:
  rabbit:
    queue:
      exchange:
        topic: demo_topic_exchange
        direct: demo_direct_exchange
      user_like_queue:
        cnt_consumers: 1
        queue_name: user_like_queue
        routing_key: user_like_routing_key

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0

posts:
  api:
    url: "https://jsonplaceholder.typicode.com"