spring:
  rabbitmq:
    password: ${RABBITMQ_PASSWORD:guest}
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    listener:
      simple:
        retry:
          initial-interval: '1000'
          enabled: 'true'
          multiplier: '2.0'
          max-attempts: '3'
    virtual-host: ${RABBITMQ_VHOST:/}

# RabbitMQ: Queues
amqp:
  rabbit:
    queue:
      exchange:
        topic: demo_topic_exchange
        direct: demo_direct_exchange
      user_like_queue:
        cnt_consumers: 1
        queue_name: user_like_queue
        routing_key: user_like_routing_key